info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
dataSource:
  driverClassName: com.mysql.cj.jdbc.Driver
  username: root
  password: ''
  pooled: true
  jmxExport: true
environments:
  development:
    dataSource:
      dbCreate: create-drop
      url: jdbc:mysql://localhost:3306/ujicoba
  test:
    dataSource:
      dbCreate: update
      url: jdbc:mysql://localhost:3306/ujicoba
  production:
    dataSource:
      dbCreate: none
      url: jdbc:mysql://localhost:3306/ujicoba
      properties:
        jmxEnabled: true
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
grails:
  codegen:
    defaultPackage: com.ilal
  profile: web
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
  views:
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
    default:
      codec: html
server:
  port: 8081
keycloak:
  realm: jiiahhhh
  auth-server-url: http://localhost:8080/realms/jiiahhhh
  resource: my-grails-app
  credentials:
    secret: lHiDnWCmcHUzqevvcDsF0gwzHizU3J20
  use-resource-role-mappings: true
  bearer-only: false
  confidential-port: 0
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/jiiahhhh
        registration:
          keycloak:
            client-id: my-grails-app
            client-secret: lHiDnWCmcHUzqevvcDsF0gwzHizU3J20
            redirect-uri: http://localhost:8081/public
            scope:
              - openid